### ISSUE TITLE
Compatibility with Zabbix 3.0

### ISSUE THREAD

**Issue by colicab** [htaira/glubix#6]
Hi htaira,

I just tried to import the template Template_App_Gluster_v2.xml in Zabbix 3.0 but I got some import errors. I presume the current templates aren't compatible with Zabbix 3.0.

Just interested if you were planning on upgrading these to Zabbix v3?

Cheers

**Comment by colicab** [comment]
Never mind, I converted it myself. Wasn't that much work.

One of the templates made compatible for Zabbix v3.0

Cheers

[Template_App_Gluster_v2_ZABv3.txt](https://github.com/htaira/glubix/files/199626/Template_App_Gluster_v2_ZABv3.txt)

**Comment by htaira** [comment]
Thanks for your feedback.
I don't have Zabbix 3.0 environment. But also I want to test Glubix templates with Zabbix 3.0

**Comment by colicab** [comment]
Turns out Zabbix 3.0 needs some additional fields by default. 
A few other fields needed to be altered in order for it to work. 

I only have 3.0 so I didn't check if it's backwards compatible. Perhaps try to import this one (changed extension to .txt) and see if it works.

Cheers

**Comment by colicab** [comment]
I have a question (bit off topic): do you have additional templates to use the gluster specific user parameters you made?

**Comment by htaira** [comment]
Why don't I provide user parameter in Glubix template?
Because zabbix 2.0 rejected entry of user parameters when loading Glubix template.

See also
https://github.com/htaira/glubix/issues/4

**Comment by htaira** [comment]
HI colicab,

Thanks for your feedback. I merged your contribution into Template_App_Gluster_v3.xml.
Also I added template file of Gluster-Swift.

Thanks,
